INVENTORIES_CA_ei = {
    "Cu concentrate from Au mine": ("gold-silver mine operation and beneficiation", "copper concentrate, sulfide ore", 'CA-QC'),
    "Cu concentrate from Cu mine": ("copper mine operation and beneficiation, sulfide ore", "copper concentrate, sulfide ore", 'CA'),
    "Au-Ag ingot": ("gold-silver mine operation and beneficiation", "gold-silver, ingot", "CA-QC"),
    "Pb concentrate": ("gold-silver mine operation and beneficiation", "lead concentrate", "CA-QC"),
    "Zn concentrate": ("gold-silver mine operation and beneficiation", "zinc concentrate", "CA-QC"),
    "Au refined": ("gold-silver mine operation with refinery", "gold", "CA-QC"),
    "Ag refined": ("gold-silver mine operation with refinery", "silver", "CA-QC"),
    "Fe concentrate": ("iron ore mine operation and beneficiation", "iron ore concentrate", "CA-QC"),
    "Ni concentrate": ("nickel mine operation and benefication to nickel concentrate, 16% Ni", "nickel concentrate, 16% Ni", "CA-QC"), #typo in EI
}


INVENTORIES_CA_reg = {
    "Cu concentrate from Au mine": ("gold-silver mine operation and beneficiation", "copper concentrate, sulfide ore", 'CA'),
    "Cu concentrate from Cu mine": ("copper mine operation and beneficiation, sulfide ore", "copper concentrate, sulfide ore", 'CA'),
    "Au-Ag ingot": ("gold-silver mine operation and beneficiation", "gold-silver, ingot", "CA"),
    "Pb concentrate": ("gold-silver mine operation and beneficiation", "lead concentrate", "CA"),
    "Zn concentrate": ("gold-silver mine operation and beneficiation", "zinc concentrate", "CA"),
    "Au refined": ("gold-silver mine operation with refinery", "gold", "CA"),
    "Ag refined": ("gold-silver mine operation with refinery", "silver", "CA"),
    "Fe concentrate": ("iron ore mine operation and beneficiation", "iron ore concentrate", "CA"),
    "Ni concentrate": ("nickel mine operation and benefication to nickel concentrate, 16% Ni", "nickel concentrate, 16% Ni", "CA"), #typo in EI
}


INVENTORIES_metallican_ore = {
    "Brucejack": ("Au, Underground mining and beneficiation at Brucejack", "Gold, silver", "CA-BC"),
    "Canadian Malartic": ("Au and Ag, Open-pit mining and beneficiation at Canadian Malartic", "Gold, silver", "CA-QC"),
    "Casa Berardi": ("Au and Ag, Open-pit and underground mining and beneficiation at Casa Berardi", "Gold, silver", "CA-QC"),
    "Detour Lake": ("Au and Ag, Open-pit mining and beneficiation at Detour Lake", "Gold", "CA-ON"),
    "Eagle River": ("Au, Underground mining and beneficiation at Eagle River", "Gold", "CA-ON"),
    "Éléonore": ("Au, Underground mining and beneficiation at Éléonore", "Gold", "CA-QC"),
    "Goldex": ("Au and Ag and Zn, Underground mining and beneficiation at Goldex", "Gold, silver", "CA-QC"),
    "Hemlo (Williams)": ("Au, Open-pit and underground mining and beneficiation at Hemlo (Williams)", "Gold", "CA-ON"),
    "Kiena": ("Au, Open-pit mining and beneficiation at Kiena", "Gold", "CA-QC"),
    "Lamaque": ("Au, Underground mining and beneficiation at Lamaque", "Gold", "CA-QC"),
    "LaRonde": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at LaRonde", "Gold, zinc, copper, silver, cadmium", "CA-QC"),
    "Macassa": ("Au, Underground mining and beneficiation at Macassa", "Gold, silver", "CA-ON"),
    "Meliadine": ("Au and Ag, Open-pit and underground mining and beneficiation at Meliadine", "Gold", "CA-NU"),
    "Musselwhite": ("Au, Underground mining and beneficiation at Musselwhite", "Gold, silver", "CA-ON"),
    "New Afton": ("Au and Cu, Underground mining and beneficiation at New Afton", "Gold, copper, silver", "CA-BC"),
    "Rainy River": ("Au, Open-pit and underground mining and beneficiation at Rainy River", "Gold, silver", "CA-ON"),
    "Red Chris": ("Au and Cu, Open-pit mining and beneficiation at Red Chris", "Gold, copper, silver", "CA-BC"),
    "Red Lake": ("Au, Underground mining and beneficiation at Red Lake", "Gold, silver", "CA-ON"),
    "Westwood-Doyon": ("Au, Underground mining and beneficiation at Westwood-Doyon", "Gold, silver", "CA-QC"),
    "Young-Davidson": ("Au, Underground mining and beneficiation at Young-Davidson", "Gold", "CA-ON"),
    "Meadowbank complex": ("Au and Ag, Open-pit and underground mining at Meadowbank complex", "Gold", "CA-NU"),
    "Porcupine complex": ("Au, Open-pit and underground mining at Porcupine complex", "Gold", "CA-ON"),
    "Timmins Operation": ("Au and Ag, Underground mining and beneficiation at Timmins Operation", "Gold", "CA-ON"),
    "Seabee Gold Operation": ("Au, Underground mining and beneficiation at Seabee Gold Operation", "Gold", "CA-SK"),
    "Snow Lake": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at Snow Lake", "Gold, zinc, copper, silver", "CA-MB"),
}


INVENTORIES_metallican_metal = {
    "Brucejack (Au)": ("Au, Underground mining and beneficiation at Brucejack", "Au, usable ore", "CA-BC"),
    "Canadian Malartic (Au)": ("Au and Ag, Open-pit mining and beneficiation at Canadian Malartic", "Au, usable ore", "CA-QC"),
    "Canadian Malartic (Ag)": ("Au and Ag, Open-pit mining and beneficiation at Canadian Malartic", "Ag, usable ore", "CA-QC"),
    "Casa Berardi (Au)": ("Au and Ag, Open-pit and underground mining and beneficiation at Casa Berardi", "Au, usable ore", "CA-QC"),
    "Casa Berardi (Ag)": ("Au and Ag, Open-pit and underground mining and beneficiation at Casa Berardi", "Ag, usable ore", "CA-QC"),
    "Detour Lake (Au)": ("Au and Ag, Open-pit mining and beneficiation at Detour Lake", "Au, usable ore", "CA-ON"),
    "Detour Lake (Ag)": ("Au and Ag, Open-pit mining and beneficiation at Detour Lake", "Ag, usable ore", "CA-ON"),
    "Eagle River (Au)": ("Au, Underground mining and beneficiation at Eagle River", "Au, usable ore", "CA-ON"),
    "Éléonore (Au)": ("Au and Ag, Underground mining and beneficiation at Éléonore", "Au, usable ore", "CA-QC"),
    "Éléonore (Ag)": ("Au and Ag, Underground mining and beneficiation at Éléonore", "Ag, usable ore", "CA-QC"),
    "Goldex (Au)": ("Au and Ag and Zn, Underground mining and beneficiation at Goldex", "Au, usable ore", "CA-QC"),
    "Goldex (Ag)": ("Au and Ag and Zn, Underground mining and beneficiation at Goldex", "Ag, usable ore", "CA-QC"),
    "Goldex (Zn)": ("Au and Ag and Zn, Underground mining and beneficiation at Goldex", "Zn, usable ore", "CA-QC"),
    "Hemlo (Au)": ("Au, Open-pit and underground mining and beneficiation at Hemlo (Williams)", "Au, usable ore", "CA-ON"),
    "Kiena (Au)": ("Au and Ag, Open-pit mining and beneficiation at Kiena", "Au, usable ore", "CA-QC"),
    "Kiena (Ag)": ("Au and Ag, Open-pit mining and beneficiation at Kiena", "Ag, usable ore", "CA-QC"),
    "Lamaque (Au)": ("Au and Ag, Underground mining and beneficiation at Lamaque", "Au, usable ore", "CA-QC"),
    "Lamaque (Ag)": ("Au and Ag, Underground mining and beneficiation at Lamaque", "Ag, usable ore", "CA-QC"),
    "LaRonde (Au)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at LaRonde", "Au, usable ore", "CA-QC"),
    "LaRonde (Ag)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at LaRonde", "Ag, usable ore", "CA-QC"),
    "LaRonde (Cu)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at LaRonde", "Cu, usable ore", "CA-QC"),
    "LaRonde (Zn)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at LaRonde", "Zn, usable ore", "CA-QC"),
    "Macassa (Au)": ("Au, Underground mining and beneficiation at Macassa", "Au, usable ore", "CA-ON"),
    "Meliadine (Au)": ("Au and Ag, Open-pit and underground mining and beneficiation at Meliadine", "Au, usable ore", "CA-NU"),
    "Meliadine (Ag)": ("Au and Ag, Open-pit and underground mining and beneficiation at Meliadine", "Ag, usable ore", "CA-NU"),
    "Musselwhite (Au)": ("Au, Underground mining and beneficiation at Musselwhite", "Au, usable ore", "CA-ON"),
    "New Afton (Au)": ("Au and Cu, Underground mining and beneficiation at New Afton", "Au, usable ore", "CA-BC"),
    "New Afton (Cu)": ("Au and Cu, Underground mining and beneficiation at New Afton", "Cu, usable ore", "CA-BC"),
    "Rainy River (Au)": ("Au, Open-pit and underground mining and beneficiation at Rainy River", "Au, usable ore", "CA-ON"),
    "Red Chris (Au)": ("Au and Cu, Open-pit mining and beneficiation at Red Chris", "Au, usable ore", "CA-BC"),
    "Red Chris (Cu)": ("Au and Cu, Open-pit mining and beneficiation at Red Chris", "Cu, usable ore", "CA-BC"),
    "Red Lake (Au)": ("Au, Underground mining and beneficiation at Red Lake", "Au, usable ore", "CA-ON"),
    "Westwood-Doyon (Au)": ("Au and Ag, Underground mining and beneficiation at Westwood-Doyon", "Au, usable ore", "CA-QC"),
    "Westwood-Doyon (Ag)": ("Au and Ag, Underground mining and beneficiation at Westwood-Doyon", "Ag, usable ore", "CA-QC"),
    "Young-Davidson (Au)": ("Au, Underground mining and beneficiation at Young-Davidson", "Au, usable ore", "CA-ON"),
    "Meadowbank complex (Au)": ("Au and Ag, Open-pit and underground mining at Meadowbank complex", "Au, usable ore", "CA-NU"),
    "Meadowbank complex (Ag)": ("Au and Ag, Open-pit and underground mining at Meadowbank complex", "Ag, usable ore", "CA-NU"),
    "Porcupine complex (Au)": ("Au, Open-pit and underground mining at Porcupine complex", "Au, usable ore", "CA-ON"),
    "Timmins Operation (Au)": ("Au and Ag, Underground mining and beneficiation at Timmins Operation", "Au, usable ore", "CA-ON"),
    "Timmins Operation (Ag)": ("Au and Ag, Underground mining and beneficiation at Timmins Operation", "Ag, usable ore", "CA-ON"),
    "Seabee Gold Operation (Au)": ("Au, Underground mining and beneficiation at Seabee Gold Operation", "Au, usable ore", "CA-SK"),
    "Snow Lake (Au)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at Snow Lake", "Au, usable ore", "CA-MB"),
    "Snow Lake (Ag)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at Snow Lake", "Ag, usable ore", "CA-MB"),
    "Snow Lake (Cu)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at Snow Lake", "Cu, usable ore", "CA-MB"),
    "Snow Lake (Zn)": ("Au and Ag and Cu and Zn, Underground mining and beneficiation at Snow Lake", "Zn, usable ore", "CA-MB"),
}
